package io.jenkins.telemetry.jenkins;

import hudson.EnvVars;import hudson.Extension;import hudson.model.*;import io.jenkins.telemetry.api.*;import io.jenkins.telemetry.core.DetachedOperation;import org.jenkinsci.plugins.workflow.actions.*;import org.jenkinsci.plugins.workflow.cps.nodes.*;import org.jenkinsci.plugins.workflow.flow.GraphListener;import org.jenkinsci.plugins.workflow.graph.FlowNode;

@Extension
public final class TelemetryStageGraphListener implements GraphListener.Synchronous {
    @Override public void onNewHead(FlowNode node){try{Object executable=node.getExecution().getOwner().getExecutable();if(!(executable instanceof Run<?,?> run))return;TaskListener listener=node.getExecution().getOwner().getListener();JenkinsTelemetryRuntime.RunSession session=JenkinsTelemetryRuntime.session(run,listener,new EnvVars());if(node instanceof StepStartNode start&&isStage(start))startStage(session,start);else if(node instanceof StepEndNode end&&isStage(end.getStartNode()))endStage(session,end);session.save();}catch(Exception ignored){}}
    private static boolean isStage(StepStartNode n){return n.getDescriptor()!=null&&"stage".equals(n.getDescriptor().getFunctionName());}
    private static void startStage(JenkinsTelemetryRuntime.RunSession s,StepStartNode n){TelemetryRunAction state=s.action();if(state.flowNodeOperation(n.getId())!=null)return;LabelAction label=n.getAction(LabelAction.class);String name=label==null||label.getDisplayName()==null?n.getDisplayName():label.getDisplayName();DetachedOperation root=state.rootOperation();DetachedOperation stage=s.engine().startDetached(OperationSpec.builder(name,OperationKind.STAGE).attributes(Attributes.builder().put("jenkins.flow_node.id",n.getId()).put("jenkins.stage.name",name).build().asMap()).build(),root==null?null:root.traceId(),root==null?null:root.spanId());state.putOperation(stage);state.flowNodeOperation(n.getId(),stage.operationId());}
    private static void endStage(JenkinsTelemetryRuntime.RunSession s,StepEndNode n){String id=s.action().removeFlowNodeOperation(n.getStartNode().getId());if(id==null)return;DetachedOperation op=s.action().removeOperation(id);if(op==null)return;ErrorAction error=n.getError();if(error==null)s.engine().completeDetached(op,SpanStatus.OK,"OK",s.correlationFor(op));else{Throwable f=error.getError();String message=f==null||f.getMessage()==null?"Stage failed":f.getMessage();DetachedOperation failed=op.withAttribute("error.type",f==null?"jenkins.stage.error":f.getClass().getName()).withAttribute("error.message",message);s.engine().completeDetached(failed,SpanStatus.ERROR,message,s.correlationFor(failed));}}
}
